### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ChristopherL-STCU** [notebookPowerTools/vscode-kusto#54]
Running a query which previously ran successfully now results in the error:

> Unexpected error occurred (Something went wrong while running the query)

Looking in VS Code's Log output this is the error:

> [2022-02-07 10:27:56.467] [renderer1] [error] [Extension Host] Failures in statusbar TypeError: Cannot read property 'length' of undefined
> 	at s.provideCellStatusBarItems (c:\Users\christopherl\.vscode-insiders\extensions\donjayamanne.kusto-0.3.8\out\extension\index.js:2:6122851)
> 	at R.$provideNotebookCellStatusBarItems (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:144028)
> 	at i._doInvokeHandler (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
> 	at i._invokeHandler (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
> 	at i._receiveRequest (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
> 	at i._receiveOneMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
> 	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
> 	at l.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
> 	at s.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
> 	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
> 	at l.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
> 	at s.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
> 	at a._receiveMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
> 	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
> 	at l.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
> 	at _.acceptChunk (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
> 	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
> 	at Socket.A (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
> 	at Socket.emit (events.js:315:20)
> 	at addChunk (internal/streams/readable.js:309:12)
> 	at readableAddChunk (internal/streams/readable.js:284:9)
> 	at Socket.Readable.push (internal/streams/readable.js:223:10)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

The version information is:

- Kusto Notebooks: v0.3.8
- .NET Interactive Notebooks: v1.0.3103010
- VS Code
  > Version: 1.64.0-insider (system setup)
  > Commit: 4af3e141defad7b6b96aa1e831f4b50f78abbe6d
  > Date: 2022-01-28T05:15:27.497Z
  > Electron: 13.5.2
  > Chromium: 91.0.4472.164
  > Node.js: 14.16.0
  > V8: 9.1.269.39-electron.0
  > OS: Windows_NT x64 10.0.19044

Let me know if any additional information will be helpful.

**Comment by ag-ramachandran** [comment]
Will get this fixed in 0.6.0 version
